# -*- coding: utf-8 -*-
"""Data_StoryTelling+Alexander Sothmann.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_OB1lI8oJ76I0NPvJCUOO0l57jiQqvLc
"""

import streamlit as st
import pandas as pd
import numpy as np





DATA_URL = ('https://raw.githubusercontent.com/dataista93/Proyecto-Coderhouse/main/DATOS/df_casos_final.csv')

@st.cache_data
def load_data(nrows):
    data = pd.read_csv(DATA_URL, nrows=nrows)
    lowercase = lambda x: str(x).lower()
    data.rename(lowercase, axis='columns', inplace=True)
    return data

data_load_state = st.text('Loading data...')
data = load_data(10000)
data_load_state.text("Done! (using st.cache_data)")

if st.checkbox('Show raw data'):
    st.subheader('Raw data')
    st.write(data)